# Generated by Django 3.2.7 on 2021-09-19 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210918_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='receive_notification_time',
            field=models.IntegerField(default=30, help_text='Time after meal start to receive notification message.'),
        ),
    ]
