# Generated by Django 3.2.7 on 2021-09-19 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_receive_notification_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='default_location',
            field=models.CharField(default='Baker College', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='receive_notification_time',
            field=models.IntegerField(default=30, help_text='Time in minutes after meal start to receive notification message.'),
        ),
    ]
