# Generated by Django 3.2.7 on 2021-09-18 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210917_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='dishappearance',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='slug',
        ),
    ]
