# Generated by Django 3.2.7 on 2021-09-18 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_review_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servery',
            options={'ordering': ['name'], 'verbose_name_plural': 'Serveries'},
        ),
    ]
