# Generated by Django 3.2.7 on 2021-09-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_servery_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.URLField(blank=True, help_text='Enter a link to an image hosted on the internet', max_length=250, null=True),
        ),
    ]
